apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue

spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: blue

  template:
    metadata:
      labels:
        app: myapp
        version: blue

    spec:
      containers:
      - name: app
        image: hashicorp/http-echo
        args:
        - "-text=This is the blue version of myapp"

        ports:
        - containerPort: 5678
      #   volumeMounts:
      #   - name: html
      #     mountPath: /usr/share/nginx/html
      # volumes:
      # - name: html
      #   configMap:
      #     name: blue-html
