apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green

spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: green

  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo
        args:
        - "-text=This is the green version of myapp"
