apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  labels:
    app: nginx
    tier: frontend

spec:
  replicas: 10
  revisionHistoryLimit: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: nginx
      tier: frontend

  template:
    metadata:
      labels:
        app: nginx
        tier: frontend

    spec:
      containers:
      - name: nginx-container
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"

        env:
        - name: ENVIRONMENT
          value: "production"
