apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app: nginx-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app

  template:
    metadata:
      labels:
        app: nginx-app

    spec:
      containers:
      - name: php-container
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 5m
            memory: 6Mi

          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  labels:
    app: nginx-app

spec:
  type: ClusterIP
  selector:
    app: nginx-app

  ports:
  - port: 80
    targetPort: 80

# kubectl create ns as
#kubectl apply -f deployment-1.yaml
#kubectl apply -f hpa.yaml
# kubectl delete deployment <deploymentName> -n as
# kubectl delete hpa <hpadeployment> -n as
